# Generated by Django 3.1.5 on 2021-02-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assigner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlesubject',
            name='duration',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='singlesubject',
            name='end_time',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='singlesubject',
            name='invigi_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='singlesubject',
            name='num_of_students',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='singlesubject',
            name='room_num',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='singlesubject',
            name='start_time',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='singlesubject',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
